/*****************************************************************************/
/*                                                                           */
/*  Generated by HHGrace Design Service Department                           */
/*  Created:  25/04/2013 by Library Group                                    */
/*  Process Name: GA90NS7L0                                                  */
/*  Revision :V0.1                                                           */
/*                                                                           */
/*****************************************************************************/
`timescale 1 ns/1 ps
`celldefine
//zxjian,20220320,chaned to 256*32bit
//module  sram128X32C2V4(
module  sram128X32C2V4(
   Q,
   CLK,
   CEN,
   WEB,
   A,
   D,
   OEN
);
   parameter		   BITS = 32;
//   parameter		   word_depth = 128;
   parameter		   word_depth = 256;
//   parameter		   addr_width = 7;
   parameter		   addr_width = 8;
   parameter               mask_width = 32 ;
   parameter               wp_size    = 1 ;
   parameter		   maskx = {mask_width{1'bx}};
   parameter		   wordx = {BITS{1'bx}};
   parameter		   addrx = {addr_width{1'bx}};
	
   output [BITS-1:0] Q;
   input CLK;
   input CEN;
   input [BITS-1:0] WEB;
   input [addr_width-1:0] A;
   input [BITS-1:0] D;
   input OEN;


//synopsys translate_off
   reg [BITS-1:0]	   mem [word_depth-1:0];

   reg			   NOT_CEN;
   reg			   NOT_WEB0;
   reg			   NOT_WEB1;
   reg			   NOT_WEB2;
   reg			   NOT_WEB3;
   reg			   NOT_WEB4;
   reg			   NOT_WEB5;
   reg			   NOT_WEB6;
   reg			   NOT_WEB7;
   reg			   NOT_WEB8;
   reg			   NOT_WEB9;
   reg			   NOT_WEB10;
   reg			   NOT_WEB11;
   reg			   NOT_WEB12;
   reg			   NOT_WEB13;
   reg			   NOT_WEB14;
   reg			   NOT_WEB15;
   reg			   NOT_WEB16;
   reg			   NOT_WEB17;
   reg			   NOT_WEB18;
   reg			   NOT_WEB19;
   reg			   NOT_WEB20;
   reg			   NOT_WEB21;
   reg			   NOT_WEB22;
   reg			   NOT_WEB23;
   reg			   NOT_WEB24;
   reg			   NOT_WEB25;
   reg			   NOT_WEB26;
   reg			   NOT_WEB27;
   reg			   NOT_WEB28;
   reg			   NOT_WEB29;
   reg			   NOT_WEB30;
   reg			   NOT_WEB31;
   reg [mask_width-1:0]    NOT_WEB;

   reg			   NOT_A0;
   reg			   NOT_A1;
   reg			   NOT_A2;
   reg			   NOT_A3;
   reg			   NOT_A4;
   reg			   NOT_A5;
   reg			   NOT_A6;
   reg [addr_width-1:0]	   NOT_A;
   reg			   NOT_D0;
   reg			   NOT_D1;
   reg			   NOT_D2;
   reg			   NOT_D3;
   reg			   NOT_D4;
   reg			   NOT_D5;
   reg			   NOT_D6;
   reg			   NOT_D7;
   reg			   NOT_D8;
   reg			   NOT_D9;
   reg			   NOT_D10;
   reg			   NOT_D11;
   reg			   NOT_D12;
   reg			   NOT_D13;
   reg			   NOT_D14;
   reg			   NOT_D15;
   reg			   NOT_D16;
   reg			   NOT_D17;
   reg			   NOT_D18;
   reg			   NOT_D19;
   reg			   NOT_D20;
   reg			   NOT_D21;
   reg			   NOT_D22;
   reg			   NOT_D23;
   reg			   NOT_D24;
   reg			   NOT_D25;
   reg			   NOT_D26;
   reg			   NOT_D27;
   reg			   NOT_D28;
   reg			   NOT_D29;
   reg			   NOT_D30;
   reg			   NOT_D31;
   reg [BITS-1:0]	   NOT_D;
   reg			   NOT_CLK_PER;
   reg			   NOT_CLK_MINH;
   reg			   NOT_CLK_MINL;

   reg			   LAST_NOT_CEN;
   reg [mask_width-1:0]	   LAST_NOT_WEB;
   reg [addr_width-1:0]	   LAST_NOT_A;
   reg [BITS-1:0]	   LAST_NOT_D;
   reg			   LAST_NOT_CLK_PER;
   reg			   LAST_NOT_CLK_MINH;
   reg			   LAST_NOT_CLK_MINL;


   wire [BITS-1:0]   _Q;
   wire			   _OENi;
   wire [addr_width-1:0]   _A;
   wire			   _CLK;
   wire			   _CEN;
   wire			   _OEN;
   wire [mask_width-1:0]   _WEB;

   wire [BITS-1:0]   _D;
   wire                    re_flag;
   wire                    re_data_flag0;
   wire                    re_data_flag1;
   wire                    re_data_flag2;
   wire                    re_data_flag3;
   wire                    re_data_flag4;
   wire                    re_data_flag5;
   wire                    re_data_flag6;
   wire                    re_data_flag7;
   wire                    re_data_flag8;
   wire                    re_data_flag9;
   wire                    re_data_flag10;
   wire                    re_data_flag11;
   wire                    re_data_flag12;
   wire                    re_data_flag13;
   wire                    re_data_flag14;
   wire                    re_data_flag15;
   wire                    re_data_flag16;
   wire                    re_data_flag17;
   wire                    re_data_flag18;
   wire                    re_data_flag19;
   wire                    re_data_flag20;
   wire                    re_data_flag21;
   wire                    re_data_flag22;
   wire                    re_data_flag23;
   wire                    re_data_flag24;
   wire                    re_data_flag25;
   wire                    re_data_flag26;
   wire                    re_data_flag27;
   wire                    re_data_flag28;
   wire                    re_data_flag29;
   wire                    re_data_flag30;
   wire                    re_data_flag31;


   reg			   LATCHED_CEN;
   reg	[mask_width-1:0]  LATCHED_WEB;
   reg [addr_width-1:0]	   LATCHED_A;
   reg [BITS-1:0]	   LATCHED_D;

   reg			   CENi;
   reg [mask_width-1:0]	   WEBi;
   reg [addr_width-1:0]	   Ai;
   reg [BITS-1:0]	   Di;
   reg [BITS-1:0]	   Qi;
   reg [BITS-1:0]	   LAST_Qi;



   reg			   LAST_CLK;

   reg [BITS-1:0]          dummy;
   integer mask_section ;
   integer lsb, msb  ;




   task update_notifier_buses;
   begin
      NOT_A = {
               NOT_A6,
               NOT_A5,
               NOT_A4,
               NOT_A3,
               NOT_A2,
               NOT_A1,
               NOT_A0};
      NOT_D = {
               NOT_D31,
               NOT_D30,
               NOT_D29,
               NOT_D28,
               NOT_D27,
               NOT_D26,
               NOT_D25,
               NOT_D24,
               NOT_D23,
               NOT_D22,
               NOT_D21,
               NOT_D20,
               NOT_D19,
               NOT_D18,
               NOT_D17,
               NOT_D16,
               NOT_D15,
               NOT_D14,
               NOT_D13,
               NOT_D12,
               NOT_D11,
               NOT_D10,
               NOT_D9,
               NOT_D8,
               NOT_D7,
               NOT_D6,
               NOT_D5,
               NOT_D4,
               NOT_D3,
               NOT_D2,
               NOT_D1,
               NOT_D0};
      NOT_WEB = {
                NOT_WEB31,
                NOT_WEB30,
                NOT_WEB29,
                NOT_WEB28,
                NOT_WEB27,
                NOT_WEB26,
                NOT_WEB25,
                NOT_WEB24,
                NOT_WEB23,
                NOT_WEB22,
                NOT_WEB21,
                NOT_WEB20,
                NOT_WEB19,
                NOT_WEB18,
                NOT_WEB17,
                NOT_WEB16,
                NOT_WEB15,
                NOT_WEB14,
                NOT_WEB13,
                NOT_WEB12,
                NOT_WEB11,
                NOT_WEB10,
                NOT_WEB9,
                NOT_WEB8,
                NOT_WEB7,
                NOT_WEB6,
                NOT_WEB5,
                NOT_WEB4,
                NOT_WEB3,
                NOT_WEB2,
                NOT_WEB1,
                NOT_WEB0};
   end
   endtask

   task mem_cycle;
   begin
    for (mask_section=0;mask_section<mask_width; mask_section=mask_section+1)
    begin
      lsb = (mask_section)*(wp_size) ;
      msb = BITS <= (lsb+wp_size-1) ? (BITS-1) : (lsb+wp_size-1) ;
      casez({WEBi[mask_section],CENi})

	2'b10: begin
	   read_mem(1,0);
	end
	2'b00: begin
	   write_mem(Ai,Di);
	   read_mem(0,0);
	end
	2'b?1: ;
	2'b1x: begin
	   read_mem(0,1);
	end
	2'bx0: begin
	   write_mem_x(Ai);
	   read_mem(0,1);
	end
	2'b0x,
	2'bxx: begin
	   write_mem_x(Ai);
	   read_mem(0,1);
	end
      endcase
   end
   end
   endtask
      

   task update_last_notifiers;
   begin
      LAST_NOT_A = NOT_A;
      LAST_NOT_D = NOT_D;
      LAST_NOT_WEB = NOT_WEB;
      LAST_NOT_CEN = NOT_CEN;
      LAST_NOT_CLK_PER = NOT_CLK_PER;
      LAST_NOT_CLK_MINH = NOT_CLK_MINH;
      LAST_NOT_CLK_MINL = NOT_CLK_MINL;
   end
   endtask

   task latch_inputs;
   begin
      LATCHED_A = _A ;
      LATCHED_D = _D ;
      LATCHED_WEB = _WEB ;
      LATCHED_CEN = _CEN ;
      LAST_Qi = Qi;
   end
   endtask


   task update_logic;
   begin
      CENi = LATCHED_CEN;
      WEBi = LATCHED_WEB;
      Ai = LATCHED_A;
      Di = LATCHED_D;
   end
   endtask



   task x_inputs;
      integer n;
   begin
      for (n=0; n<addr_width; n=n+1)
	 begin
	    LATCHED_A[n] = (NOT_A[n]!==LAST_NOT_A[n]) ? 1'bx : LATCHED_A[n] ;
	 end
      for (n=0; n<BITS; n=n+1)
	 begin
	    LATCHED_D[n] = (NOT_D[n]!==LAST_NOT_D[n]) ? 1'bx : LATCHED_D[n] ;
	 end
      for (n=0; n<mask_width; n=n+1)
	 begin
	    LATCHED_WEB[n] = (NOT_WEB[n]!==LAST_NOT_WEB[n]) ? 1'bx : LATCHED_WEB[n] ;
         end

      LATCHED_CEN = (NOT_CEN!==LAST_NOT_CEN) ? 1'bx : LATCHED_CEN ;
   end
   endtask

   task read_mem;
      input r_wb;
      input xflag;
      integer i ;
   begin
      if (r_wb)
	 begin
	    if (valid_address(Ai))
	       begin
                  dummy = mem[Ai] ;
                  for (i=lsb;i<=msb;i=i+1) Qi[i] = dummy[i] ;
	       end
	    else
	       begin
	          x_mem;
                  for (i=lsb;i<=msb;i=i+1) Qi[i] = 1'bx ;
	       end
	 end
      else
	 begin
	    if (xflag)
	       begin
                  for (i=lsb;i<=msb;i=i+1) Qi[i] = 1'bx ;
	       end
	    else
	       begin
                  for (i=lsb;i<=msb;i=i+1) Qi[i] = dummy[i] ;
	       end
	 end
   end
   endtask

   task write_mem;
      input [addr_width-1:0] a;
      input [BITS-1:0] d;
   integer i;
 
   begin
      casez({valid_address(a)})
	1'b0: 
		begin
			x_mem;
                	for (i=lsb; i<=msb; i=i+1)  dummy[i] = d[i] ;
		end
        1'b1 : begin
		dummy= mem[a];
                for (i=lsb; i<=msb; i=i+1)  dummy[i] = d[i] ;
                mem[a]=dummy;
              end
      endcase
   end
   endtask

   task write_mem_x;
      input [addr_width-1:0] a;
   integer i;
   begin
      casez({valid_address(a)})
	1'b0: 
		begin
			x_mem;
                	for (i=lsb; i<=msb; i=i+1)  dummy[i] = 1'bx ;
		end
        1'b1 : begin
		dummy= mem[a];
                for (i=lsb; i<=msb; i=i+1)  dummy[i] = 1'bx ;
                mem[a]=dummy;
              end
      endcase
   end
   endtask

   task x_mem;
      integer n;
   begin
      for (n=0; n<word_depth; n=n+1)
	 mem[n]=wordx;
   end
   endtask

   task process_violations;
   begin
      if ((NOT_CLK_PER!==LAST_NOT_CLK_PER) ||
	  (NOT_CLK_MINH!==LAST_NOT_CLK_MINH) ||
	  (NOT_CLK_MINL!==LAST_NOT_CLK_MINL))
	 begin
	    if (CENi !== 1'b1)
               begin
		  x_mem;
		  Qi = wordx ;
	       end
	 end
      else
	 begin
	    update_notifier_buses;
	    x_inputs;
	    update_logic;
	    mem_cycle;
	 end
      update_last_notifiers;
   end
   endtask

   function valid_address;
      input [addr_width-1:0] a;
   begin
      valid_address = (^(a) !== 1'bx);
   end
   endfunction


   bufif0 (Q[0], _Q[0], _OENi);
   bufif0 (Q[1], _Q[1], _OENi);
   bufif0 (Q[2], _Q[2], _OENi);
   bufif0 (Q[3], _Q[3], _OENi);
   bufif0 (Q[4], _Q[4], _OENi);
   bufif0 (Q[5], _Q[5], _OENi);
   bufif0 (Q[6], _Q[6], _OENi);
   bufif0 (Q[7], _Q[7], _OENi);
   bufif0 (Q[8], _Q[8], _OENi);
   bufif0 (Q[9], _Q[9], _OENi);
   bufif0 (Q[10], _Q[10], _OENi);
   bufif0 (Q[11], _Q[11], _OENi);
   bufif0 (Q[12], _Q[12], _OENi);
   bufif0 (Q[13], _Q[13], _OENi);
   bufif0 (Q[14], _Q[14], _OENi);
   bufif0 (Q[15], _Q[15], _OENi);
   bufif0 (Q[16], _Q[16], _OENi);
   bufif0 (Q[17], _Q[17], _OENi);
   bufif0 (Q[18], _Q[18], _OENi);
   bufif0 (Q[19], _Q[19], _OENi);
   bufif0 (Q[20], _Q[20], _OENi);
   bufif0 (Q[21], _Q[21], _OENi);
   bufif0 (Q[22], _Q[22], _OENi);
   bufif0 (Q[23], _Q[23], _OENi);
   bufif0 (Q[24], _Q[24], _OENi);
   bufif0 (Q[25], _Q[25], _OENi);
   bufif0 (Q[26], _Q[26], _OENi);
   bufif0 (Q[27], _Q[27], _OENi);
   bufif0 (Q[28], _Q[28], _OENi);
   bufif0 (Q[29], _Q[29], _OENi);
   bufif0 (Q[30], _Q[30], _OENi);
   bufif0 (Q[31], _Q[31], _OENi);
   buf (_D[0], D[0]);
   buf (_D[1], D[1]);
   buf (_D[2], D[2]);
   buf (_D[3], D[3]);
   buf (_D[4], D[4]);
   buf (_D[5], D[5]);
   buf (_D[6], D[6]);
   buf (_D[7], D[7]);
   buf (_D[8], D[8]);
   buf (_D[9], D[9]);
   buf (_D[10], D[10]);
   buf (_D[11], D[11]);
   buf (_D[12], D[12]);
   buf (_D[13], D[13]);
   buf (_D[14], D[14]);
   buf (_D[15], D[15]);
   buf (_D[16], D[16]);
   buf (_D[17], D[17]);
   buf (_D[18], D[18]);
   buf (_D[19], D[19]);
   buf (_D[20], D[20]);
   buf (_D[21], D[21]);
   buf (_D[22], D[22]);
   buf (_D[23], D[23]);
   buf (_D[24], D[24]);
   buf (_D[25], D[25]);
   buf (_D[26], D[26]);
   buf (_D[27], D[27]);
   buf (_D[28], D[28]);
   buf (_D[29], D[29]);
   buf (_D[30], D[30]);
   buf (_D[31], D[31]);
   buf (_A[0], A[0]);
   buf (_A[1], A[1]);
   buf (_A[2], A[2]);
   buf (_A[3], A[3]);
   buf (_A[4], A[4]);
   buf (_A[5], A[5]);
   buf (_A[6], A[6]);
   buf (_A[7], A[7]); //zxjian,20220320
   buf (_CLK, CLK);
   buf (_WEB[0], WEB[0]);
   buf (_WEB[1], WEB[1]);
   buf (_WEB[2], WEB[2]);
   buf (_WEB[3], WEB[3]);
   buf (_WEB[4], WEB[4]);
   buf (_WEB[5], WEB[5]);
   buf (_WEB[6], WEB[6]);
   buf (_WEB[7], WEB[7]);
   buf (_WEB[8], WEB[8]);
   buf (_WEB[9], WEB[9]);
   buf (_WEB[10], WEB[10]);
   buf (_WEB[11], WEB[11]);
   buf (_WEB[12], WEB[12]);
   buf (_WEB[13], WEB[13]);
   buf (_WEB[14], WEB[14]);
   buf (_WEB[15], WEB[15]);
   buf (_WEB[16], WEB[16]);
   buf (_WEB[17], WEB[17]);
   buf (_WEB[18], WEB[18]);
   buf (_WEB[19], WEB[19]);
   buf (_WEB[20], WEB[20]);
   buf (_WEB[21], WEB[21]);
   buf (_WEB[22], WEB[22]);
   buf (_WEB[23], WEB[23]);
   buf (_WEB[24], WEB[24]);
   buf (_WEB[25], WEB[25]);
   buf (_WEB[26], WEB[26]);
   buf (_WEB[27], WEB[27]);
   buf (_WEB[28], WEB[28]);
   buf (_WEB[29], WEB[29]);
   buf (_WEB[30], WEB[30]);
   buf (_WEB[31], WEB[31]);
   buf (_OEN, OEN);
   buf (_CEN, CEN);


   assign _OENi = _OEN;
   assign _Q = Qi;
   assign re_flag = !(_CEN);
   assign re_data_flag0 = !(_CEN || _WEB[0]);
   assign re_data_flag1 = !(_CEN || _WEB[1]);
   assign re_data_flag2 = !(_CEN || _WEB[2]);
   assign re_data_flag3 = !(_CEN || _WEB[3]);
   assign re_data_flag4 = !(_CEN || _WEB[4]);
   assign re_data_flag5 = !(_CEN || _WEB[5]);
   assign re_data_flag6 = !(_CEN || _WEB[6]);
   assign re_data_flag7 = !(_CEN || _WEB[7]);
   assign re_data_flag8 = !(_CEN || _WEB[8]);
   assign re_data_flag9 = !(_CEN || _WEB[9]);
   assign re_data_flag10 = !(_CEN || _WEB[10]);
   assign re_data_flag11 = !(_CEN || _WEB[11]);
   assign re_data_flag12 = !(_CEN || _WEB[12]);
   assign re_data_flag13 = !(_CEN || _WEB[13]);
   assign re_data_flag14 = !(_CEN || _WEB[14]);
   assign re_data_flag15 = !(_CEN || _WEB[15]);
   assign re_data_flag16 = !(_CEN || _WEB[16]);
   assign re_data_flag17 = !(_CEN || _WEB[17]);
   assign re_data_flag18 = !(_CEN || _WEB[18]);
   assign re_data_flag19 = !(_CEN || _WEB[19]);
   assign re_data_flag20 = !(_CEN || _WEB[20]);
   assign re_data_flag21 = !(_CEN || _WEB[21]);
   assign re_data_flag22 = !(_CEN || _WEB[22]);
   assign re_data_flag23 = !(_CEN || _WEB[23]);
   assign re_data_flag24 = !(_CEN || _WEB[24]);
   assign re_data_flag25 = !(_CEN || _WEB[25]);
   assign re_data_flag26 = !(_CEN || _WEB[26]);
   assign re_data_flag27 = !(_CEN || _WEB[27]);
   assign re_data_flag28 = !(_CEN || _WEB[28]);
   assign re_data_flag29 = !(_CEN || _WEB[29]);
   assign re_data_flag30 = !(_CEN || _WEB[30]);
   assign re_data_flag31 = !(_CEN || _WEB[31]);


   always @(
	    NOT_A0 or
	    NOT_A1 or
	    NOT_A2 or
	    NOT_A3 or
	    NOT_A4 or
	    NOT_A5 or
	    NOT_A6 or
	    NOT_D0 or
	    NOT_D1 or
	    NOT_D2 or
	    NOT_D3 or
	    NOT_D4 or
	    NOT_D5 or
	    NOT_D6 or
	    NOT_D7 or
	    NOT_D8 or
	    NOT_D9 or
	    NOT_D10 or
	    NOT_D11 or
	    NOT_D12 or
	    NOT_D13 or
	    NOT_D14 or
	    NOT_D15 or
	    NOT_D16 or
	    NOT_D17 or
	    NOT_D18 or
	    NOT_D19 or
	    NOT_D20 or
	    NOT_D21 or
	    NOT_D22 or
	    NOT_D23 or
	    NOT_D24 or
	    NOT_D25 or
	    NOT_D26 or
	    NOT_D27 or
	    NOT_D28 or
	    NOT_D29 or
	    NOT_D30 or
	    NOT_D31 or
	    NOT_WEB0 or
	    NOT_WEB1 or
	    NOT_WEB2 or
	    NOT_WEB3 or
	    NOT_WEB4 or
	    NOT_WEB5 or
	    NOT_WEB6 or
	    NOT_WEB7 or
	    NOT_WEB8 or
	    NOT_WEB9 or
	    NOT_WEB10 or
	    NOT_WEB11 or
	    NOT_WEB12 or
	    NOT_WEB13 or
	    NOT_WEB14 or
	    NOT_WEB15 or
	    NOT_WEB16 or
	    NOT_WEB17 or
	    NOT_WEB18 or
	    NOT_WEB19 or
	    NOT_WEB20 or
	    NOT_WEB21 or
	    NOT_WEB22 or
	    NOT_WEB23 or
	    NOT_WEB24 or
	    NOT_WEB25 or
	    NOT_WEB26 or
	    NOT_WEB27 or
	    NOT_WEB28 or
	    NOT_WEB29 or
	    NOT_WEB30 or
	    NOT_WEB31 or
	    NOT_CEN or
	    NOT_CLK_PER or
	    NOT_CLK_MINH or
	    NOT_CLK_MINL
	    )
      begin
         process_violations;
      end

   always @( _CLK )
      begin
         casez({LAST_CLK,_CLK})
	   2'b01: begin
	      latch_inputs;
	      update_logic;
	      mem_cycle;
	   end

	   2'b10,
	   2'bx?,
	   2'b00,
	   2'b11: ;

	   2'b?x: begin
	      x_mem;
              read_mem(0,1);
	   end
	   
	 endcase
	 LAST_CLK = _CLK;
      end

   specify
      $setuphold(posedge CLK, posedge CEN, 1.000, 0.500, NOT_CEN);
      $setuphold(posedge CLK, negedge CEN, 1.000, 0.500, NOT_CEN);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[0], 1.000, 0.500, NOT_WEB0);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[0], 1.000, 0.500, NOT_WEB0);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[1], 1.000, 0.500, NOT_WEB1);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[1], 1.000, 0.500, NOT_WEB1);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[2], 1.000, 0.500, NOT_WEB2);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[2], 1.000, 0.500, NOT_WEB2);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[3], 1.000, 0.500, NOT_WEB3);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[3], 1.000, 0.500, NOT_WEB3);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[4], 1.000, 0.500, NOT_WEB4);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[4], 1.000, 0.500, NOT_WEB4);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[5], 1.000, 0.500, NOT_WEB5);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[5], 1.000, 0.500, NOT_WEB5);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[6], 1.000, 0.500, NOT_WEB6);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[6], 1.000, 0.500, NOT_WEB6);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[7], 1.000, 0.500, NOT_WEB7);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[7], 1.000, 0.500, NOT_WEB7);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[8], 1.000, 0.500, NOT_WEB8);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[8], 1.000, 0.500, NOT_WEB8);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[9], 1.000, 0.500, NOT_WEB9);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[9], 1.000, 0.500, NOT_WEB9);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[10], 1.000, 0.500, NOT_WEB10);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[10], 1.000, 0.500, NOT_WEB10);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[11], 1.000, 0.500, NOT_WEB11);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[11], 1.000, 0.500, NOT_WEB11);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[12], 1.000, 0.500, NOT_WEB12);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[12], 1.000, 0.500, NOT_WEB12);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[13], 1.000, 0.500, NOT_WEB13);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[13], 1.000, 0.500, NOT_WEB13);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[14], 1.000, 0.500, NOT_WEB14);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[14], 1.000, 0.500, NOT_WEB14);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[15], 1.000, 0.500, NOT_WEB15);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[15], 1.000, 0.500, NOT_WEB15);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[16], 1.000, 0.500, NOT_WEB16);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[16], 1.000, 0.500, NOT_WEB16);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[17], 1.000, 0.500, NOT_WEB17);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[17], 1.000, 0.500, NOT_WEB17);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[18], 1.000, 0.500, NOT_WEB18);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[18], 1.000, 0.500, NOT_WEB18);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[19], 1.000, 0.500, NOT_WEB19);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[19], 1.000, 0.500, NOT_WEB19);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[20], 1.000, 0.500, NOT_WEB20);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[20], 1.000, 0.500, NOT_WEB20);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[21], 1.000, 0.500, NOT_WEB21);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[21], 1.000, 0.500, NOT_WEB21);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[22], 1.000, 0.500, NOT_WEB22);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[22], 1.000, 0.500, NOT_WEB22);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[23], 1.000, 0.500, NOT_WEB23);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[23], 1.000, 0.500, NOT_WEB23);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[24], 1.000, 0.500, NOT_WEB24);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[24], 1.000, 0.500, NOT_WEB24);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[25], 1.000, 0.500, NOT_WEB25);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[25], 1.000, 0.500, NOT_WEB25);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[26], 1.000, 0.500, NOT_WEB26);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[26], 1.000, 0.500, NOT_WEB26);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[27], 1.000, 0.500, NOT_WEB27);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[27], 1.000, 0.500, NOT_WEB27);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[28], 1.000, 0.500, NOT_WEB28);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[28], 1.000, 0.500, NOT_WEB28);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[29], 1.000, 0.500, NOT_WEB29);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[29], 1.000, 0.500, NOT_WEB29);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[30], 1.000, 0.500, NOT_WEB30);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[30], 1.000, 0.500, NOT_WEB30);
      $setuphold(posedge CLK &&& re_flag, posedge WEB[31], 1.000, 0.500, NOT_WEB31);
      $setuphold(posedge CLK &&& re_flag, negedge WEB[31], 1.000, 0.500, NOT_WEB31);
      $setuphold(posedge CLK &&& re_flag, posedge A[0], 1.000, 0.500, NOT_A0);
      $setuphold(posedge CLK &&& re_flag, negedge A[0], 1.000, 0.500, NOT_A0);
      $setuphold(posedge CLK &&& re_flag, posedge A[1], 1.000, 0.500, NOT_A1);
      $setuphold(posedge CLK &&& re_flag, negedge A[1], 1.000, 0.500, NOT_A1);
      $setuphold(posedge CLK &&& re_flag, posedge A[2], 1.000, 0.500, NOT_A2);
      $setuphold(posedge CLK &&& re_flag, negedge A[2], 1.000, 0.500, NOT_A2);
      $setuphold(posedge CLK &&& re_flag, posedge A[3], 1.000, 0.500, NOT_A3);
      $setuphold(posedge CLK &&& re_flag, negedge A[3], 1.000, 0.500, NOT_A3);
      $setuphold(posedge CLK &&& re_flag, posedge A[4], 1.000, 0.500, NOT_A4);
      $setuphold(posedge CLK &&& re_flag, negedge A[4], 1.000, 0.500, NOT_A4);
      $setuphold(posedge CLK &&& re_flag, posedge A[5], 1.000, 0.500, NOT_A5);
      $setuphold(posedge CLK &&& re_flag, negedge A[5], 1.000, 0.500, NOT_A5);
      $setuphold(posedge CLK &&& re_flag, posedge A[6], 1.000, 0.500, NOT_A6);
      $setuphold(posedge CLK &&& re_flag, negedge A[6], 1.000, 0.500, NOT_A6);
      $setuphold(posedge CLK &&& re_data_flag0, posedge D[0],1.000, 0.500, NOT_D0);
      $setuphold(posedge CLK &&& re_data_flag0, negedge D[0],1.000, 0.500, NOT_D0);
      $setuphold(posedge CLK &&& re_data_flag1, posedge D[1],1.000, 0.500, NOT_D1);
      $setuphold(posedge CLK &&& re_data_flag1, negedge D[1],1.000, 0.500, NOT_D1);
      $setuphold(posedge CLK &&& re_data_flag2, posedge D[2],1.000, 0.500, NOT_D2);
      $setuphold(posedge CLK &&& re_data_flag2, negedge D[2],1.000, 0.500, NOT_D2);
      $setuphold(posedge CLK &&& re_data_flag3, posedge D[3],1.000, 0.500, NOT_D3);
      $setuphold(posedge CLK &&& re_data_flag3, negedge D[3],1.000, 0.500, NOT_D3);
      $setuphold(posedge CLK &&& re_data_flag4, posedge D[4],1.000, 0.500, NOT_D4);
      $setuphold(posedge CLK &&& re_data_flag4, negedge D[4],1.000, 0.500, NOT_D4);
      $setuphold(posedge CLK &&& re_data_flag5, posedge D[5],1.000, 0.500, NOT_D5);
      $setuphold(posedge CLK &&& re_data_flag5, negedge D[5],1.000, 0.500, NOT_D5);
      $setuphold(posedge CLK &&& re_data_flag6, posedge D[6],1.000, 0.500, NOT_D6);
      $setuphold(posedge CLK &&& re_data_flag6, negedge D[6],1.000, 0.500, NOT_D6);
      $setuphold(posedge CLK &&& re_data_flag7, posedge D[7],1.000, 0.500, NOT_D7);
      $setuphold(posedge CLK &&& re_data_flag7, negedge D[7],1.000, 0.500, NOT_D7);
      $setuphold(posedge CLK &&& re_data_flag8, posedge D[8],1.000, 0.500, NOT_D8);
      $setuphold(posedge CLK &&& re_data_flag8, negedge D[8],1.000, 0.500, NOT_D8);
      $setuphold(posedge CLK &&& re_data_flag9, posedge D[9],1.000, 0.500, NOT_D9);
      $setuphold(posedge CLK &&& re_data_flag9, negedge D[9],1.000, 0.500, NOT_D9);
      $setuphold(posedge CLK &&& re_data_flag10, posedge D[10],1.000, 0.500, NOT_D10);
      $setuphold(posedge CLK &&& re_data_flag10, negedge D[10],1.000, 0.500, NOT_D10);
      $setuphold(posedge CLK &&& re_data_flag11, posedge D[11],1.000, 0.500, NOT_D11);
      $setuphold(posedge CLK &&& re_data_flag11, negedge D[11],1.000, 0.500, NOT_D11);
      $setuphold(posedge CLK &&& re_data_flag12, posedge D[12],1.000, 0.500, NOT_D12);
      $setuphold(posedge CLK &&& re_data_flag12, negedge D[12],1.000, 0.500, NOT_D12);
      $setuphold(posedge CLK &&& re_data_flag13, posedge D[13],1.000, 0.500, NOT_D13);
      $setuphold(posedge CLK &&& re_data_flag13, negedge D[13],1.000, 0.500, NOT_D13);
      $setuphold(posedge CLK &&& re_data_flag14, posedge D[14],1.000, 0.500, NOT_D14);
      $setuphold(posedge CLK &&& re_data_flag14, negedge D[14],1.000, 0.500, NOT_D14);
      $setuphold(posedge CLK &&& re_data_flag15, posedge D[15],1.000, 0.500, NOT_D15);
      $setuphold(posedge CLK &&& re_data_flag15, negedge D[15],1.000, 0.500, NOT_D15);
      $setuphold(posedge CLK &&& re_data_flag16, posedge D[16],1.000, 0.500, NOT_D16);
      $setuphold(posedge CLK &&& re_data_flag16, negedge D[16],1.000, 0.500, NOT_D16);
      $setuphold(posedge CLK &&& re_data_flag17, posedge D[17],1.000, 0.500, NOT_D17);
      $setuphold(posedge CLK &&& re_data_flag17, negedge D[17],1.000, 0.500, NOT_D17);
      $setuphold(posedge CLK &&& re_data_flag18, posedge D[18],1.000, 0.500, NOT_D18);
      $setuphold(posedge CLK &&& re_data_flag18, negedge D[18],1.000, 0.500, NOT_D18);
      $setuphold(posedge CLK &&& re_data_flag19, posedge D[19],1.000, 0.500, NOT_D19);
      $setuphold(posedge CLK &&& re_data_flag19, negedge D[19],1.000, 0.500, NOT_D19);
      $setuphold(posedge CLK &&& re_data_flag20, posedge D[20],1.000, 0.500, NOT_D20);
      $setuphold(posedge CLK &&& re_data_flag20, negedge D[20],1.000, 0.500, NOT_D20);
      $setuphold(posedge CLK &&& re_data_flag21, posedge D[21],1.000, 0.500, NOT_D21);
      $setuphold(posedge CLK &&& re_data_flag21, negedge D[21],1.000, 0.500, NOT_D21);
      $setuphold(posedge CLK &&& re_data_flag22, posedge D[22],1.000, 0.500, NOT_D22);
      $setuphold(posedge CLK &&& re_data_flag22, negedge D[22],1.000, 0.500, NOT_D22);
      $setuphold(posedge CLK &&& re_data_flag23, posedge D[23],1.000, 0.500, NOT_D23);
      $setuphold(posedge CLK &&& re_data_flag23, negedge D[23],1.000, 0.500, NOT_D23);
      $setuphold(posedge CLK &&& re_data_flag24, posedge D[24],1.000, 0.500, NOT_D24);
      $setuphold(posedge CLK &&& re_data_flag24, negedge D[24],1.000, 0.500, NOT_D24);
      $setuphold(posedge CLK &&& re_data_flag25, posedge D[25],1.000, 0.500, NOT_D25);
      $setuphold(posedge CLK &&& re_data_flag25, negedge D[25],1.000, 0.500, NOT_D25);
      $setuphold(posedge CLK &&& re_data_flag26, posedge D[26],1.000, 0.500, NOT_D26);
      $setuphold(posedge CLK &&& re_data_flag26, negedge D[26],1.000, 0.500, NOT_D26);
      $setuphold(posedge CLK &&& re_data_flag27, posedge D[27],1.000, 0.500, NOT_D27);
      $setuphold(posedge CLK &&& re_data_flag27, negedge D[27],1.000, 0.500, NOT_D27);
      $setuphold(posedge CLK &&& re_data_flag28, posedge D[28],1.000, 0.500, NOT_D28);
      $setuphold(posedge CLK &&& re_data_flag28, negedge D[28],1.000, 0.500, NOT_D28);
      $setuphold(posedge CLK &&& re_data_flag29, posedge D[29],1.000, 0.500, NOT_D29);
      $setuphold(posedge CLK &&& re_data_flag29, negedge D[29],1.000, 0.500, NOT_D29);
      $setuphold(posedge CLK &&& re_data_flag30, posedge D[30],1.000, 0.500, NOT_D30);
      $setuphold(posedge CLK &&& re_data_flag30, negedge D[30],1.000, 0.500, NOT_D30);
      $setuphold(posedge CLK &&& re_data_flag31, posedge D[31],1.000, 0.500, NOT_D31);
      $setuphold(posedge CLK &&& re_data_flag31, negedge D[31],1.000, 0.500, NOT_D31);

      $period(posedge CLK, 3.000, NOT_CLK_PER);
      $width(posedge CLK, 1.000, 0, NOT_CLK_MINH);
      $width(negedge CLK, 1.000, 0, NOT_CLK_MINL);

      (CLK => Q[0])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[1])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[2])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[3])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[4])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[5])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[6])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[7])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[8])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[9])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[10])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[11])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[12])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[13])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[14])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[15])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[16])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[17])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[18])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[19])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[20])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[21])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[22])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[23])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[24])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[25])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[26])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[27])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[28])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[29])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[30])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (CLK => Q[31])=(1.000, 1.000, 0.500, 1.000, 0.500, 1.000);
      (OEN => Q[0])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[1])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[2])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[3])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[4])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[5])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[6])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[7])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[8])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[9])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[10])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[11])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[12])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[13])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[14])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[15])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[16])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[17])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[18])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[19])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[20])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[21])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[22])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[23])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[24])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[25])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[26])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[27])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[28])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[29])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[30])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
      (OEN => Q[31])=(1.000, 1.000, 1.000, 1.000, 1.000, 1.000);
   endspecify

//synopsys translate_on
endmodule
`endcelldefine
